name: NASA Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install server dependencies
        run: npm install

      - name: Install client dependencies
        run: npm install --prefix client

      - name: Build client
        run: npm run build --prefix client
