name: NASA Project CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Setup Node.js
      - name: Use Node.js version 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install server dependencies (check if package.json exists in root or server/)
      - name: Install server dependencies
        run: |
          if exist package.json (
            npm install
          ) else if exist server\package.json (
            cd server
            npm install
            cd ..
          )

      # Install client dependencies
      - name: Install client dependencies
        run: |
          if exist client\package.json (
            cd client
            npm install
            cd ..
          )

      # Build the client
      - name: Build client
        run: |
          if exist client\package.json (
            npm run build --prefix client
          )
